project:
  type: website
  output-dir: docs

website:
  title: "reimn11.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: mintty
      dark: superhero
    css: styles.css
    toc: true

editor: visual

