project:
  type: website
  output-dir: docs

website:
  #title: "Rei Miyashiro"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - resume.qmd
      - icon: github
        href: https://github.com/reimn11
        target: blank
      

format:
  html:
    theme: 
      light: mintty
      dark: superhero
    css: styles.css
    toc: true

editor: visual

